CREATE TABLE IF NOT EXISTS [Usr](
	[ID] INTEGER NOT NULL PRIMARY KEY ASC AUTOINCREMENT,
	[Login] VARCHAR(50) NOT NULL,
	[Pass] VARCHAR(50) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[IsLocked] BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS [Rol](
	[ID] INTEGER NOT NULL PRIMARY KEY ASC AUTOINCREMENT,
	[NAME] VARCHAR(50),
	[Descr] VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS [UsrRol](
	[ID] INTEGER NOT NULL PRIMARY KEY ASC AUTOINCREMENT,
	[Usr] INTEGER NOT NULL,
	[Rol] INTEGER NOT NULL,

	FOREIGN KEY(Usr) REFERENCES Usr(ID),
	FOREIGN KEY(Rol) REFERENCES Rol(ID)
);

CREATE TABLE IF NOT EXISTS [Module](
	[ID] INTEGER NOT NULL PRIMARY KEY ASC AUTOINCREMENT,
	[Name] VARCHAR(50) NOT NULL,
	[Descr] VARCHAR(100) NULL
);


CREATE TABLE IF NOT EXISTS [Log](
	[ID] INTEGER NOT NULL PRIMARY KEY ASC AUTOINCREMENT,
	[Dat] DateTime NOT NULL,
	[Usr] INTEGER NULL,
	[Module] INTEGER NULL,
	[Uri] VARCHAR(1024),
	[Data] VARCHAR(4096),

	FOREIGN KEY(Usr) REFERENCES Usr(ID),
	FOREIGN KEY([Module]) REFERENCES [dbo].[Module]([ID])
);
                       
CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_Usr_Login on Usr(Login ASC);
CREATE INDEX IF NOT EXISTS IDX_Usr_Name on Usr(Name ASC);
CREATE INDEX IF NOT EXISTS IDX_Usr_Pass on Usr(Pass ASC);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_Rol_Name on Rol(Name ASC);
CREATE INDEX IF NOT EXISTS IDX_UsrRol_Usr on UsrRol(Usr ASC);
CREATE INDEX IF NOT EXISTS IDX_UsrRol_Rol on UsrRol(Rol ASC);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_Module_Name on Module(Name ASC);

CREATE INDEX IF NOT EXISTS IDX_Log_Usr on Log(Usr ASC);
CREATE INDEX IF NOT EXISTS IDX_Log_Module on Log(Module ASC);